import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CartProvider } from "@/contexts/cart-context";
import { Toaster } from "react-hot-toast";
import CustomCursor from "@/components/ui/custom-cursor";

// Exact same font files used in korty-eo (HK Grotesk by HVD Fonts)
const hkGrotesk = localFont({
  variable: "--font-grotesk",
  display: "swap",
  src: [
    {
      path: "./fonts/Grotesk/HKGrotesk-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Grotesk/HKGrotesk-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Grotesk/HKGrotesk-Medium.woff2",
      weight: "500",
      style: "normal",
    },
  ],
});

// Exact same Fraunces72pt files used in korty-eo
const fraunces = localFont({
  variable: "--font-fraunces",
  display: "swap",
  src: [
    {
      path: "./fonts/Fraunces/Fraunces72pt-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Fraunces/Fraunces72pt-LightItalic.woff2",
      weight: "300",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "kagearchvs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${hkGrotesk.variable} ${fraunces.variable} antialiased`}>
        <CartProvider>
          <CustomCursor />
          {children}
          <Toaster
            position="top-right"
            reverseOrder={false}
            toastOptions={{
              duration: 4000,
              style: {
                background: "#fff",
                color: "#000",
                padding: "16px",
                borderRadius: "8px",
                border: "1px solid #e5e7eb",
              },
              success: {
                duration: 5000,
                iconTheme: {
                  primary: "#10b981",
                  secondary: "#fff",
                },
              },
              error: {
                duration: 6000,
                iconTheme: {
                  primary: "#ef4444",
                  secondary: "#fff",
                },
              },
            }}
          />
        </CartProvider>
      </body>
    </html>
  );
}
