import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CartProvider } from "@/contexts/cart-context";
import { Toaster } from "react-hot-toast";
import CustomCursor from "@/components/ui/custom-cursor";

// Exact same font files used in korty-eo (HK Grotesk by HVD Fonts)
const hkGrotesk = localFont({
  variable: "--font-grotesk",
  display: "swap",
  src: [
    {
      path: "./fonts/Grotesk/HKGrotesk-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Grotesk/HKGrotesk-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Grotesk/HKGrotesk-Medium.woff2",
      weight: "500",
      style: "normal",
    },
  ],
});

// Exact same Fraunces72pt files used in korty-eo
const fraunces = localFont({
  variable: "--font-fraunces",
  display: "swap",
  src: [
    {
      path: "./fonts/Fraunces/Fraunces72pt-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Fraunces/Fraunces72pt-LightItalic.woff2",
      weight: "300",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "kagearchvs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${hkGrotesk.variable} ${fraunces.variable} antialiased`}>
        <CartProvider>
          <CustomCursor />
          {children}
          <Toaster
            position="bottom-center"
            reverseOrder={false}
            toastOptions={{
              duration: 3500,
              style: {
                background:    "#111",
                color:         "#fff",
                padding:       "14px 20px",
                borderRadius:  "999px",
                fontSize:      "0.82rem",
                fontWeight:    500,
                letterSpacing: "0.02em",
                boxShadow:     "0 8px 32px rgba(0,0,0,0.18)",
                fontFamily:    "var(--font-grotesk), sans-serif",
                maxWidth:      "360px",
              },
              success: {
                duration: 3500,
                iconTheme: {
                  primary: "#fff",
                  secondary: "#111",
                },
              },
              error: {
                duration: 4500,
                iconTheme: {
                  primary: "#fff",
                  secondary: "#e53e3e",
                },
                style: {
                  background: "#e53e3e",
                },
              },
            }}
          />
        </CartProvider>
      </body>
    </html>
  );
}
